#!/bin/bash
# Write the interpreter wrapper: a drop-in `python` that runs the container venv's
# interpreter inside the image. Use it anywhere a python path is expected
# (ECA_RSI_PYTHON, PY= in a batch script, MSP_PYTHON / ZMIP_PYTHON / OSP_PYTHON).
#   ECA_CT_ROOT  venv/wrapper location  (default: $PWD)
#   ECA_SIF      image                  (required)
#   ECA_BIND     bind list              (default: /scratch,/oak,/home)
set -euo pipefail
ROOT="${ECA_CT_ROOT:-$PWD}"
: "${ECA_SIF:?set ECA_SIF to the image path}"
BIND="${ECA_BIND:-/scratch,/oak,/home}"
mkdir -p "$ROOT"
cat > "$ROOT/python" <<EOF
#!/bin/bash
# Container-only interpreter for the ecarsi chain -- generated by container/install-wrapper.sh.
# Host env (API keys, SLURM_*, XDG_CACHE_HOME, NUMBA_*) passes through, but apptainer >=1.5
# strips PYTHONPATH: forward it explicitly so a worktree override reaches this python AND
# the kernel subprocesses it spawns. APPTAINERENV_APPEND_PATH lets the image see host
# binaries that are not on its PATH (e.g. ngrok for \`ecarsi serve --ngrok\`).
SIF=\${ECA_SIF:-$ECA_SIF}
[ -n "\${PYTHONPATH:-}" ] && export APPTAINERENV_PYTHONPATH="\$PYTHONPATH"
exec apptainer exec --bind $BIND "\$SIF" $ROOT/.venv/bin/python "\$@"
EOF
chmod +x "$ROOT/python"
echo "wrote $ROOT/python -> $ECA_SIF"
if [ -x "$ROOT/.venv/bin/python" ]; then
    "$ROOT/python" -c "import ecarsi, sys; print('wrapper ok:', sys.version.split()[0], ecarsi.__file__)"
else
    echo "(no venv at $ROOT/.venv yet -- run container/build.sh first, then re-check)"
fi
