#!/bin/bash
# Write the interpreter wrapper: a drop-in `python` that runs the container venv's
# interpreter inside the image. Use it anywhere a python path is expected
# (ECA_RSI_PYTHON, PY= in a batch script, MSP_PYTHON / ZMIP_PYTHON / OSP_PYTHON).
#
#   ECA_CT_ROOT   venv/wrapper location  (default: $PWD)
#   ECA_SIF       image                  (required)
#   ECA_BIND      bind list              (default: /scratch,/oak,/home)
#   ECA_NODE_BIN  host node bin dir to expose inside the image (optional; only
#                 HARNESS=claude needs it, its CLI being a node program). The
#                 filesystem holding it must also be in ECA_BIND.
set -euo pipefail
ROOT="${ECA_CT_ROOT:-$PWD}"
: "${ECA_SIF:?set ECA_SIF to the image path}"
BIND="${ECA_BIND:-/scratch,/oak,/home}"
mkdir -p "$ROOT"

NODE_LINE=""
[ -n "${ECA_NODE_BIN:-}" ] && NODE_LINE="export APPTAINERENV_PREPEND_PATH=\"${ECA_NODE_BIN}\"  # HARNESS=claude needs node"

cat > "$ROOT/python" <<'TEMPLATE'
#!/bin/bash
# Container-only interpreter for the ecarsi chain -- generated by container/install-wrapper.sh.
# Host env (API keys, SLURM_*, XDG_CACHE_HOME, NUMBA_*) passes through, but apptainer >= 1.5
# strips PYTHONPATH, so it is forwarded explicitly below -- a worktree override has to reach
# this python AND every kernel subprocess it spawns.
#
# To let the image see a host binary that is not on its PATH (ngrok, for
# `ecarsi serve --ngrok`), export APPTAINERENV_APPEND_PATH for that call.
SIF=${ECA_SIF:-@SIF@}
# Only PYTHONPATH segments under the project filesystems are forwarded. The
# whitelist is the point of this block, not tidiness: a login shell that has run
# "ml load" carries the module tree's site-packages in PYTHONPATH, and if that
# tree is inside the bind list the container resolves it. py-cupy, for one, hard
# depends on py-numpy 1.26.3 and would silently shadow the venv's numpy -- one of
# the fifteen package versions ecarsi writes into every downstream stage
# identity. That kind of shadowing is invisible until a stage fails to verify.
# Worktree overrides live under /scratch and pass through untouched.
if [ -n "${PYTHONPATH:-}" ]; then
    _pp=$(printf '%s' "$PYTHONPATH" | tr ':' '\n' | grep -E '^(/scratch|/oak|/home)/' | paste -sd:)
    [ -n "$_pp" ] && export APPTAINERENV_PYTHONPATH="$_pp"
fi
@NODE@
exec apptainer exec --bind @BIND@ "$SIF" @ROOT@/.venv/bin/python "$@"
TEMPLATE

python3 - "$ROOT/python" "$ECA_SIF" "$BIND" "$ROOT" "$NODE_LINE" <<'PY'
import sys, pathlib
path, sif, bind, root, node = sys.argv[1:6]
p = pathlib.Path(path)
s = p.read_text().replace("@SIF@", sif).replace("@BIND@", bind).replace("@ROOT@", root)
s = s.replace("@NODE@\n", node + "\n" if node else "")
p.write_text(s)
PY
chmod +x "$ROOT/python"
echo "wrote $ROOT/python -> $ECA_SIF"
if [ -x "$ROOT/.venv/bin/python" ]; then
    "$ROOT/python" -c "import ecarsi, sys; print('wrapper ok:', sys.version.split()[0], ecarsi.__file__)"
else
    echo "(no venv at $ROOT/.venv yet -- run container/build.sh first, then re-check)"
fi
